// @ts-check
import { defineConfig } from 'astro/config';
import rehypeGuideBlocks from './src/plugins/rehype-guide-blocks.mjs';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import starlightTags from 'starlight-tags';

export default defineConfig({
  markdown: { rehypePlugins: [rehypeGuideBlocks] },
  redirects: {
    '/concepts': '/start/start-here/',
    '/concepts/agents/agentic-harness': '/agents/agentic-harness/',
    '/concepts/agents/chat-agent-workflow-automation': '/start/chat-agent-workflow-automation/',
    '/concepts/agents/evals': '/running/evals/',
    '/concepts/agents/human-in-the-loop': '/agents/human-in-the-loop/',
    '/concepts/agents/mcp': '/agents/mcp/',
    '/concepts/agents/memory': '/agents/memory/',
    '/concepts/agents/observability': '/running/observability/',
    '/concepts/agents/skills-and-instruction-files': '/agents/skills-and-instruction-files/',
    '/concepts/agents/subagents-and-multi-agent-systems': '/agents/subagents-and-multi-agent-systems/',
    '/concepts/agents/the-agent-loop': '/agents/the-agent-loop/',
    '/concepts/agents/tool-use': '/agents/tool-use/',
    '/concepts/cost/estimating-cost-per-task': '/running/estimating-cost-per-task/',
    '/concepts/cost/how-ai-pricing-works': '/running/how-api-pricing-works/',
    '/concepts/cost/model-routing': '/running/model-routing/',
    '/concepts/cost/prompt-caching-and-batch-processing': '/running/prompt-caching-and-batch-processing/',
    '/concepts/data/apis-oauth-and-api-keys': '/agents/apis-oauth-and-api-keys/',
    '/concepts/data/entity-resolution': '/data/entity-resolution/',
    '/concepts/data/how-llms-talk-to-databases': '/data/how-llms-talk-to-databases/',
    '/concepts/data/keeping-data-fresh': '/data/keeping-data-fresh/',
    '/concepts/data/knowledge-graphs': '/data/knowledge-graphs/',
    '/concepts/data/permissions-and-access-control': '/data/permissions-and-access-control/',
    '/concepts/data/rag-and-chunking': '/data/rag-and-chunking/',
    '/concepts/data/structured-vs-unstructured-data': '/data/structured-vs-unstructured-data/',
    '/concepts/data/types-of-databases': '/data/types-of-databases/',
    '/concepts/data/what-a-context-layer-is': '/data/what-a-context-layer-is/',
    '/concepts/how-models-work/benchmarks': '/under-the-hood/benchmarks/',
    '/concepts/how-models-work/embeddings': '/data/embeddings/',
    '/concepts/how-models-work/fine-tuning-vs-prompting-vs-rag': '/data/fine-tuning-vs-prompting-vs-rag/',
    '/concepts/how-models-work/hallucination-and-grounding': '/start/hallucination-and-grounding/',
    '/concepts/how-models-work/inference': '/under-the-hood/inference/',
    '/concepts/how-models-work/llms-lrms-and-lqms': '/under-the-hood/llms-lrms-and-lqms/',
    '/concepts/how-models-work/multimodal-models': '/using-ai/multimodal-models/',
    '/concepts/how-models-work/open-vs-closed-weights': '/under-the-hood/open-vs-closed-weights/',
    '/concepts/how-models-work/parameters-and-temperature': '/under-the-hood/parameters-and-temperature/',
    '/concepts/how-models-work/pre-training-and-post-training': '/under-the-hood/pre-training-and-post-training/',
    '/concepts/how-models-work/quantisation': '/under-the-hood/quantisation/',
    '/concepts/how-models-work/reasoning-models': '/using-ai/reasoning-models/',
    '/concepts/how-models-work/tokens-and-context-windows': '/start/tokens-and-context-windows/',
    '/concepts/how-models-work/what-an-llm-is': '/start/what-an-llm-is/',
    '/concepts/running-things/environment-variables-and-secrets': '/building/environment-variables-and-secrets/',
    '/concepts/running-things/orchestration-tools': '/building/orchestration-tools/',
    '/concepts/running-things/rate-limits-retries-and-failures': '/running/rate-limits-retries-and-failures/',
    '/concepts/running-things/serverless-functions': '/building/serverless-functions/',
    '/concepts/running-things/triggers-and-scheduling': '/building/triggers-and-scheduling/',
    '/concepts/security/audit-trails': '/running/audit-trails/',
    '/concepts/security/data-exfiltration-through-tools': '/running/data-exfiltration-through-tools/',
    '/concepts/security/gdpr-data-retention-and-dpas': '/running/gdpr-data-retention-and-dpas/',
    '/concepts/security/least-privilege': '/running/least-privilege/',
    '/concepts/security/prompt-injection': '/running/prompt-injection/',
    '/concepts/talking-to-models/context-engineering': '/data/context-engineering/',
    '/concepts/talking-to-models/prompt-engineering': '/using-ai/prompt-engineering/',
    '/concepts/talking-to-models/structured-outputs': '/building/structured-outputs/',
    '/concepts/talking-to-models/system-prompts': '/using-ai/system-prompts/',
    '/setup': '/building/claude-code-and-the-api/',
    '/setup/claude-code-in-depth': '/building/claude-code-in-depth/',
    '/setup/claude-surfaces': '/building/claude-code-and-the-api/',
    '/setup/connecting-business-tools-through-mcp': '/building/connecting-business-tools-through-mcp/',
    '/setup/cursor-and-app-builders': '/building/cursor-and-app-builders/',
    '/setup/git-and-github-for-one': '/building/git-and-github/',
    '/setup/n8n': '/building/n8n/',
    '/setup/not-burning-tokens': '/using-ai/not-burning-tokens/',
    '/setup/recommended-settings': '/using-ai/recommended-settings/',
    '/setup/supabase': '/building/supabase/',
    '/setup/terminal-basics': '/building/terminal-basics/',
    '/setup/vercel': '/building/vercel/',
    '/setup/your-first-agent': '/building/your-first-agent/',
    '/start-here/confusables': '/reference/confusables/',
    '/start-here/glossary': '/reference/glossary/',
    '/start-here/how-to-use': '/start/start-here/',
    '/start-here/learning-path': '/start/start-here/',
    '/start-here/recently-added': '/reference/recently-added/',
  },
  site: 'https://agentic-guide.vercel.app',
  integrations: [
    // Mermaid must come before Starlight so diagrams render inside docs pages
    mermaid({ theme: 'neutral', autoTheme: true }),
    starlight({
      title: 'Agentic AI Field Guide',
      description: 'A plain-language, growing guide to agentic AI.',
      lastUpdated: true,
      plugins: [starlightTags()],
      customCss: [
        '@fontsource/literata/400.css',
        '@fontsource/literata/400-italic.css',
        '@fontsource/literata/600.css',
        '@fontsource/public-sans/400.css',
        '@fontsource/public-sans/600.css',
        '@fontsource/public-sans/700.css',
        './src/styles/custom.css',
      ],
      components: {
        PageTitle: './src/components/PageTitle.astro',
      },
      sidebar: [
        { label: '1. Start here', collapsed: true, items: [{ autogenerate: { directory: 'start' } }] },
        { label: '2. Using AI well', collapsed: true, items: [{ autogenerate: { directory: 'using-ai' } }] },
        { label: '3. How agents work', collapsed: true, items: [{ autogenerate: { directory: 'agents' } }] },
        { label: '4. Building your own', collapsed: true, items: [{ autogenerate: { directory: 'building' } }] },
        { label: '5. Data and the context layer', collapsed: true, items: [{ autogenerate: { directory: 'data' } }] },
        { label: '6. Running it for real', collapsed: true, items: [{ autogenerate: { directory: 'running' } }] },
        { label: '7. Under the hood', collapsed: true, items: [{ autogenerate: { directory: 'under-the-hood' } }] },
        {
          label: 'Electives',
          collapsed: true,
          items: [
            { label: 'The map', collapsed: true, items: [{ autogenerate: { directory: 'map' } }] },
            { label: 'Model landscape', collapsed: true, items: [{ autogenerate: { directory: 'models' } }] },
            { label: 'Comms channels', collapsed: true, items: [{ autogenerate: { directory: 'channels' } }] },
          ],
        },
        {
          label: 'Reference',
          collapsed: true,
          items: [
            'reference/glossary',
            'reference/confusables',
            { label: 'Browse by tag', link: '/tags/' },
            'reference/recently-added',
          ],
        },
      ],
    }),
  ],
});
